# Generated by Django 2.2.5 on 2019-12-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, related_name='children', to='compsystems.HierarchicalModel')),
                ('name', models.CharField(max_length=1024, unique=True, verbose_name='name')),
                ('context', models.TextField(max_length=10000, verbose_name='context')),
            ],
            options={
                'verbose_name': 'hierarchical model',
                'verbose_name_plural': 'hierarchical models',
            },
        ),
    ]
